linters:
  enable-all: true
  disable:
    - execinquery # Deprecated
    - gomnd # Deprecated
    - exhaustruct
    # TODO re-enable these
    - err113
    - funlen
    - godox
    - gofumpt
    - nlreturn
    - paralleltest
    - testifylint
    - tparallel
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  lll:
    line-length: 140
issues:
  exclude-rules:
    - path: example/
      linters:
        - depguard
        - forbidigo
    - path: _test\.go
      linters:
        - depguard
