linters:
  enable-all: true
  disable:
    - execinquery # Deprecated
    - gomnd # Deprecated
    - exhaustruct
    # TODO re-enable these
    - depguard
    - err113
    - forbidigo
    - funlen
    - godox
    - gofumpt
    - lll
    - nlreturn
    - paralleltest
    - testifylint
    - tparallel
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
